######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 3 14:13:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baltsu.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += baltsu.cpp main.cpp mainwindow.cpp
